name: Report Bug | 报告BUG
description: "Report bug"
title: "[Bug]: "
labels: []
body:
  - type: dropdown
    id: download
    attributes:
      label: Installation Method | 安装方法与平台
      options:
        - Pip (please confirm: used latest requirements.txt)
        - Anaconda (please confirm: used latest requirements.txt)
        - Docker（Windows/Mac）
        - Docker（Linux）
        - Docker-Compose（Windows/Mac）
        - Docker-Compose（Linux）
        - Huggingface
        - Others
    validations:
      required: true
    
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug & Screen Shot | 简述 与 有帮助的截图
      description: Describe the bug & Screen Shot | 简述 与 有帮助的截图
    validations:
      required: true

  - type: textarea
    id: traceback
    attributes:
      label: Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）
      description: Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）






